[build]
  command = "npm run build:prod"
  publish = "dist"

[build.environment]
  VITE_API_BASE_URL = "https://bdnode.onrender.com/api"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"