services:
  - type: static
    name: etech-frontend
    buildCommand: npm install && npm run build:prod
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://etech-backend.onrender.com/api