services:
  - type: web
    name: fdreact
    env: node
    region: oregon
    plan: starter
    buildCommand: npm install && npm run build:prod
    startCommand: npx serve -s dist -l 3000
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: VITE_API_BASE_URL
        value: https://bdnode.onrender.com/api
    autoDeploy: true